version: '3'
services:
  server:
    build: ./server
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
      - pnpm-store:/root/.pnpm-store
volumes:
    pnpm-store:
